# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore NuGet Packages
        run: nuget restore "Momentum Rich Presence.sln"

      - name: Build and Publish Web App
        run: msbuild "Momentum Rich Presence.sln" /p:Configuration=Release
      
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: rel-artifact
          path: "Momentum Rich Presence\\bin\\Release"
          
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v3.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          release: rel-artifact

      
